version: '3'
services:
 prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
volumes:
    prowlarr:
        external: false