version: '3'
services:
 jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - AUTO_UPDATE=true
    volumes:
      - jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
volumes:
    jackett:
        external: false