version: 2
jobs:
build:
    docker:
      - image: circleci/python:3.6.2
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: <user>
          POSTGRES_DB: <db>
          PGPASSWORD: <pw>
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
      - ANSIBLE_LOCAL_TEMP: /home/circleci/.ansible/tmp
      - ANSIBLE_REMOTE_TEMP: /home/circleci/.ansible/tmp
    steps:
      - checkout
    - restore_cache:
        keys:
        - deps-{{ checksum "requirements.txt" }}
    - run:
        name: Install Dependencies
        command: |
            python3 -m venv env
            . env/bin/activate
            pip install ansible
            pip install -r requirements.txt
            sudo apt update
            sudo apt install rsync
    - save_cache:
        key: deps-{{ checksum "requirements.txt" }}
        paths:
            - "env"
    - run:
        name: Run Tests
        command: |
            . env/bin/activate
            export PYTHONPATH=.
            export TEST_MODE=1
            pytest -vs
    - store_artifacts:
        path: test-reports
        destination: test-reports

    - run:
      name: Deploy to production
      command: |
        . env/bin/activate
        ansible-playbook -i ansible/hosts ansible/deployment.yml

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master