version: '3'
services:
 resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK=000
    volumes:
      - resilio:/config
      - /nfs/media/resilio/downloads:/downloads
      - /nfs/media/resilio:/sync
    ports:
      - 8889:8888
      - 55555:55555
    restart: unless-stopped
volumes:
    resilio:
        external: false