version: '3'
services:
 sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK=000
    volumes:
      - sabnzbd:/config
      - /nfs/media:/media
    ports:
      - 8080:8080
    restart: unless-stopped
volumes:
    sabnzbd:
        external: false