---
version: "3.1"

services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: server-name
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./syncthing/config:/config
      - ./some-backup-folder:/some-backup-folder
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true