version: '3'
services:
 readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr_books
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - readarr:/config
      - /nfs/media:/media
    ports:
      - 8787:8787
    restart: unless-stopped
volumes:
    readarr:
        external: false