version: '3'
services:
 sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK=000
    volumes:
      - sonarr:/config
      - /nfs/media:/media
    ports:
      - 8989:8989
    restart: unless-stopped
volumes:
    sonarr:
        external: false