version: '3'
services:
 tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
volumes:
    tautulli:
        external: false