---
- name: Remote Update of Raspberry Pi Servers
  hosts: rpi
  become: true
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
        purge: yes    
    - name: Reboot Host(s)
      ansible.builtin.reboot:
        msg: "Reboot by Ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 10
        test_command: "whoami"
