---
- hosts: "*"
  become: true
  tasks:
    - name: deploy jellyfin docker container
      docker_container:
        image: lscr.io/linuxserver/jellyfin:latest
        name: jellyfin
        state: started
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
        ports:
          - "8096:8086"
        volumes:
          - /config
        state: absent
        restart_policy: always