---
- name: Update pihole
  hosts: 
    - pihole
  serial: 1
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
        purge: yes    
    - name: pihole Update
      shell: pihole -up
    - name: Reboot Host(s)
      ansible.builtin.reboot:
        msg: "Reboot by Ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 10
        test_command: "whoami"    
