- name: Remote Reboot of Ubuntu Servers
  hosts: "*"
  become: true
  tasks:
    - name: Reboot Host(s)
      ansible.builtin.reboot:
        msg: "reboot by Ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 10
        test_command: "whoami"
