---
- name: Setup Tailscale
  hosts: "*"
  tasks:
  - name: Download Tailscale
    shell: curl -fsSL https://tailscale.com/install.sh | sh
    
  - name: Start Tailscale
    shell: sudo tailscale up 
