---
- name: Setup Tailscale
  hosts: "*"
  #vars_prompt:
  # - name: auth_key
  #    prompt: Enter the auth key
  tasks:
  - name: Download Tailscale
    shell: curl -fsSL https://tailscale.com/install.sh | sh
    
  - name: Install | Bring Tailscale Up
    become: true
    ansible.builtin.command: tailscale up {{ tailscale_auth }}
    register: tailscale_start

   
