---
- name: Remote Download of UFW-Docker Utility
  hosts: "*"
  become: true
  tasks:
  - name: Enable UFW
    community.general.ufw:
     state: enabled
     policy: deny  
  - name: Download UFW-Docker and Set Executable
    ansible.builtin.get_url:
      url: https://github.com/chaifeng/ufw-docker/raw/master/ufw-docker
      dest: /usr/local/bin/ufw-docker
      mode: +x
  - name: Install UFW-Docker
    ansible.builtin.command: ufw-docker install
