---
- name: Setup UFW for Hyperion Server
  hosts: "*"
  become: true
  tasks:
  - name: Allow connections from Local Docker Hyperion
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
      comment: Hyperion Docker Networks
    loop:
      - 172.17.0.0/16
      - 172.18.0.0/16
  - name: Expose Port 2375 to allow Docker to report to Uptime-Kuma
    community.general.ufw:
      rule: allow
      port: '2375'
      comment: Uptime-Kuma Reporting HTTP
  - name: Expose Port 2376 to allow Docker to report to Uptime-Kuma
    community.general.ufw:
      rule: allow
      port: '2376'
      comment: Uptime-Kuma Reporting HTTPS
  - name: Expose Port 111 to allow NFS
    community.general.ufw:
      rule: allow
      port: '111'
      comment: NFS Portmapper
  - name: Expose Port 2049 to allow NFS
    community.general.ufw:
      rule: allow
      port: '2049'
      comment: Network File System (NFS) - remote filesystem access
  - name: Plex Media Server (Standard + DLNA) TCP
    community.general.ufw:
      rule: "allow"
      port: "{{ item }}"
      proto: "tcp"
      comment: Plex Media Server (Standard + DLNA) TCP
    with_items:
      - "32400"
      - "3005"
      - "8324"
      - "32469"
  - name: Plex Media Server (Standard + DLNA) UDP
    community.general.ufw:
      rule: "allow"
      port: "{{ item }}"
      proto: "udp"
      comment: Plex Media Server (Standard + DLNA) UDP
    with_items:
      - "5353"
      - "1900"
      - "32410:32414"
