---
- name: Setup UFW for Webservers
  hosts: "*"
  become: true
  tasks:
    - name: Allow NGINX Full in UFW
      community.general.ufw:
        rule: allow
        name: Nginx Full
        comment: Allow NGINX

    - name: Setup of UFW
      ansible.builtin.import_playbook: ufw.yml



