---
- name: Setup UFW for Atlas Server
  hosts: "*"
  become: true
  tasks:
  - name: Allow connections from Local Docker Atlas
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
      comment: Atlas Docker Networks
    loop:
      - 172.17.0.0/16
      - 172.23.0.0/16
  - name: Expose Port 2375 to allow Docker to report to Uptime-Kuma
    community.general.ufw:
      rule: allow
      port: '2375'
      comment: Uptime-Kuma Reporting HTTP
  - name: Expose Port 2376 to allow Docker to report to Uptime-Kuma
    community.general.ufw:
      rule: allow
      port: '2376'
      comment: Uptime-Kuma Reporting HTTPS
  - name: Expose Port 111 to allow NFS
    community.general.ufw:
      rule: allow
      port: '111'
      comment: NFS Portmapper
  - name: Expose Port 2049 to allow NFS
    community.general.ufw:
      rule: allow
      port: '2049'
      comment: Network File System (NFS) - remote filesystem access
