---
- name: Setup UFW for Webservers
  hosts: "*"
  become: true
  tasks:
    - name: Allow OpenSSH in UFW
      community.general.ufw:
        rule: allow
        name: OpenSSH
        comment: Allow OpenSSH
    - name: Allow NGINX Full in UFW
      community.general.ufw:
        rule: allow
        name: Nginx Full
        comment: Allow NGINX
    - name: Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
