---
- name: Setup of UFW
  hosts: "*"
  become: true
  tasks:
    - name: Allow OpenSSH in UFW
      community.general.ufw:
        rule: allow
        name: OpenSSH
        comment: Allow OpenSSH
    - name: Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
