version: '3'
services:
 radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK=000
    volumes:
      - radarr:/config
      - /nfs/media:/media      
    ports:
      - 7878:7878
    restart: unless-stopped
volumes:
    radarr:
        external: false