version: '3'
services:
 lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK=000
    volumes:
      - lidarr:/config
      - /nfs/media:/media
    ports:
      - 8686:8686
    restart: unless-stopped
volumes:
    lidarr:
        external: false