---
- name: Deploy SabNZBd in Docker
  hosts: "*"
  become: true
  tasks:
    - name: Create new data volume for container
      community.docker.docker_volume:
       name: sabnzbd-data
    - name: Deploy docker container
      community.docker.docker_container:
        image: lscr.io/linuxserver/sabnzbd:latest
        name: sabnzbd
        state: started
        env:
           PUID: "1000"
           PGID: "1000"
           TZ: "America/Chicago"
           UMASK: "000"
        ports:
          - "8080:8080"
        volumes:
          - sabnzbd-data:/config
          - /nfs/media:/media
        restart_policy: unless-stopped