---
- name: Deploy Radarr in Docker
  hosts: "*"
  become: true
  tasks:
    - name: Create new data volume for container
      community.docker.docker_volume:
       name: radarr-data
    - name: Deploy docker container
      community.docker.docker_container:
        image: lscr.io/linuxserver/radarr:latest
        name: radarr
        state: started
        env:
           PUID: "1000"
           PGID: "1000"
           TZ: "America/Chicago"
           UMASK: "000"
        ports:
          - "7878:7878"
        volumes:
          - radarr-data:/config
          - /nfs/media:/media
        restart_policy: unless-stopped