---
- name: Deploy Sonarr 4k in Docker
  hosts: "*"
  become: true
  tasks:
    - name: Create new data volume for container
      community.docker.docker_volume:
       name: sonarr4k-data
    - name: Deploy docker container
      community.docker.docker_container:
        image: lscr.io/linuxserver/sonarr:latest
        name: sonarr4k
        state: started
        env:
           PUID: "1000"
           PGID: "1000"
           TZ: "America/Chicago"
        ports:
          - "8888:8989"
        volumes:
          - sonarr4k-data:/config
          - /nfs/media:/media
        restart_policy: unless-stopped