---
- name: Deploy Tautulli in Docker
  hosts: "*"
  become: true
  tasks:
    - name: Create new data volume for container
      community.docker.docker_volume:
       name: tautulli-data
    - name: Deploy docker container
      community.docker.docker_container:
        image: lscr.io/linuxserver/tautulli:latest
        name: tautulli
        state: started
        env:
           PUID: "1000"
           PGID: "1000"
           TZ: "America/Chicago"
        ports:
          - "8181:8181"
        volumes:
          - tautulli-data:/config
        restart_policy: unless-stopped