---
- name: Deploy Watchtower in Docker
  hosts: "*"
  become: true
  tasks:
    - name: Deploy docker container
      community.docker.docker_container:
        image: containrrr/watchtower
        name: watchtower
        state: started
        env:
           PUID: "1000"
           PGID: "1000"
           TZ: "America/Chicago"
           WATCHTOWER_NOTIFICATION_URL: "discord://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: unless-stopped