---
- name: Deploy Prowlarr in Docker
  hosts: "*"
  become: true
  tasks:
    - name: Create new data volume for container
      community.docker.docker_volume:
       name: prowlarr-data
    - name: Deploy docker container
      community.docker.docker_container:
        image: lscr.io/linuxserver/prowlarr:develop
        name: prowlarr
        state: started
        env:
           PUID: "1000"
           PGID: "1000"
           TZ: "America/Chicago"
        ports:
          - "9696:9696"
        volumes:
          - prowlarr-data:/config
        restart_policy: unless-stopped