---
- name: Deploy Uptime Kuma in Docker
  hosts: "*"
  become: true
  tasks:
    - name: Create new data volume for container
      community.docker.docker_volume:
       name: uptime-kuma-data
    - name: Deploy docker container
      community.docker.docker_container:
        image: louislam/uptime-kuma:1
        name: uptime-kuma
        state: started
        env:
           PUID: "1000"
           PGID: "1000"
           TZ: "America/Chicago"
        ports:
          - "3001:3001"
        volumes:
          - uptime-kuma-data:/app/data
        restart_policy: unless-stopped