---
- name: Deploy Docker Containers on Atlas and Hyperion
  hosts: "*"
  become: true
  tasks:

  - import_playbook: docker-bazarr.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-bazarr4k.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-dozzle.yml

  - import_playbook: docker-flaresolverr.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-jackett.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-lidarr.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-sonarr.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-sonarr4k.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-radarr.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-radarr4k.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-tdarr.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-readarr.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-resilio-sync.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-prowlarr.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-sabnzbd.yml
    when: inventory_hostname in groups["atlas"] 

  - import_playbook: docker-watchtower.yml

  - import_playbook: docker-uptime-kuma.yml
    when: inventory_hostname in groups["hyperion"] 

  - import_playbook: docker-overseerr.yml
    when: inventory_hostname in groups["hyperion"]