---
- name: Deploy Readarr in Docker
  hosts: "*"
  become: true
  tasks:
    - name: Create new data volume for container
      community.docker.docker_volume:
       name: readarr-data
    - name: Deploy docker container
      community.docker.docker_container:
        image: lscr.io/linuxserver/readarr:develop
        name: readarr
        state: started
        env:
           PUID: "1000"
           PGID: "1000"
           TZ: "America/Chicago"
           UMASK: "000"
        ports:
          - "8787:8787"
        volumes:
          - readarr-data:/config
          - /nfs/media:/media
        restart_policy: unless-stopped