---
- name: Deploy Radarr 4k in Docker
  hosts: "*"
  become: true
  tasks:
    - name: Create new data volume for container
      community.docker.docker_volume:
       name: radarr4k-data
    - name: Deploy docker container
      community.docker.docker_container:
        image: lscr.io/linuxserver/radarr:latest
        name: radarr4k
        state: started
        env:
           PUID: "1000"
           PGID: "1000"
           TZ: "America/Chicago"
           UMASK: "000"
        ports:
          - "17878:7878"
        volumes:
          - radarr4k-data:/config
          - /nfs/media:/media
        restart_policy: unless-stopped