version: "3.8"
services:
    wg-easy:
        environment:
        - WG_HOST=some.example.com
        - PASSWORD=some-password
        - WG_PORT=51820
        - WG_DEFAULT_ADDRESS=10.8.0.x
        - WG_DEFAULT_DNS=192.168.60.10

        image: weejewel/wg-easy
        container_name: wg-easy
        volumes:
        - .:/etc/wireguard
        ports:
        - "51820:51820/udp"
        - "51821:51821/tcp"
        restart: unless-stopped
        cap_add:
        - NET_ADMIN
        - SYS_MODULE
        sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1