name: Ansible check debian:stable  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: ansible check with debian:stable
      # replace "master" with any valid ref
      uses: roles-ansible/check-ansible-debian-stable-action@master
      with:
        targets: "./"
        #  [required]
        #   Paths to your ansible role or playboox.yml you want to test
        #   Some Examples:
        #   targets: "role/my_role/"
        #   targets: "site.yml"
        #
        # group: ""
        #  [optional]
        #   When testing playbooks you have to tell ansible
        #   the group you that we write in our hosts file.
        #   example:
        #   group: 'servers'
        #
        hosts: "localhost"
        #  [optional]
        #   When testing playbooks you have to give one example
        #   host this action should use to test your playbook.
        #   > We only spawn one docker container that mean
        #   > we can only test one host at the time. Sorry
        #   some examples:
        #   hosts: 'localhost'
        #   hosts: 'srv01.example.com'
        #
        requirements: "general.6.2.0"
        #  [optional]
        #   When testing playbooks and you are using ansible galaxy,
        #   you may be interested in installing your requirements
        #   from ansible galaxy.
        #   To do this please provide us either the role name directly
        #   requirements: 'community.general.6.2.0'
        #   or your requiements.yml file.
        #   requirements: 'requirements.yml'
    - name: Perform integration testing with ansible-test
      uses: ansible-community/ansible-test-gh-action@release/v1
      with:
        ansible-core-version: stable-2.14.1
        pre-test-cmd: echo This runs before the ansible-test invocation
        target-python-version: '3.10'
        controller-python-version: auto
        testing-type: integration
        test-deps: ansible.netcommon
    - name: Perform sanity testing with ansible-test
      uses: ansible-community/ansible-test-gh-action@release/v1
      with:
        ansible-core-version: stable-2.14.1
        testing-type: sanity
    - name: Perform unit testing with ansible-test
      uses: ansible-community/ansible-test-gh-action@release/v1
      with:
        ansible-core-version: stable-2.14.1
        pre-test-cmd: echo This runs before the ansible-test invocation
        target-python-version: '3.10'
        testing-type: units
        test-deps: >-
          ansible.netcommon
          ansible.utils
