name: Ansilbe Test

- name: Perform integration testing with ansible-test
  uses: ansible-community/ansible-test-gh-action@release/v1.12.0
  with:
    ansible-core-version: stable-2.14.1
    pre-test-cmd: echo This runs before the ansible-test invocation
    target-python-version: '3.10'
    controller-python-version: auto
    testing-type: integration
    test-deps: ansible.netcommon
- name: Perform sanity testing with ansible-test
  uses: ansible-community/ansible-test-gh-action@release/v1.12.0
  with:
    ansible-core-version: stable-2.14.1
    testing-type: sanity
- name: Perform unit testing with ansible-test
  uses: ansible-community/ansible-test-gh-action@release/v1.12.0
  with:
    ansible-core-version: stable-2.14.1
    pre-test-cmd: echo This runs before the ansible-test invocation
    target-python-version: '3.10'
    testing-type: units
    test-deps: >-
      ansible.netcommon
      ansible.utils
