name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3.3.0

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2.2.0
        with:
          github_token: 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
          auto_fix: true
          black: true
          black_auto_fix: true
          flake8: true
          flake8_auto_fix: false
