name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  
jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@db41740e12847bb616a339b75eb9414e711417df 
        with:
          github_token: ${{ secrets.TOKEN }}
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
